### PR TITLE
Update OpenGL Registry

### PR DESCRIPTION
**Pull request by gurchetansingh**
OpenGL: 253836ac53b2e248fa47d96cacc18a63ac27c703

### CODE REVIEW

**Comment by gurchetansingh** [comment]
CC: @ebassi, fixed issues with https://github.com/anholt/libepoxy/pull/209 (I think).  PTAL.

Also, can we tag a new release with this MR included?

**Comment by ofourdan** [comment]
Can we update the EGL registry as well, while at it?

**Comment by gurchetansingh** [comment]
> Can we update the EGL registry as well, while at it?
>

Done.

> Alternatively, I can post a new PR for the EGL registry alone... But would be nicer to update all the registry at once, I reckon.

**Comment by ofourdan** [comment]
Thanks! :+1:

**Comment by gurchetansingh** [comment]
Ping @ebassi @anholt

**Comment by ebassi** [comment]
Thanks for reworking the PR.

You should also update the `wgl.xml` and `glx.xml` registries, though. We try to update everything in one go, instead of piecemeal.

If you could include the other API, it would be great.

Thanks again!

**Comment by gurchetansingh** [comment]
> Thanks for reworking the PR.
> 
> You should also update the `wgl.xml` and `glx.xml` registries, though.

Done.  Would be awesome if we get a new release tag from this.

> We try to update everything in one go, instead of piecemeal.
> 
> If you could include the other API, it would be great.
> 
> Thanks again!

**Comment by gurchetansingh** [comment]
Ping @ebassi

**Comment by anholt** [comment]
Looked good, so merged.  It seems the last registry update before this one didn't use the khronos-registry branch, but also looks like we have no deltas from the original registry any more.

**Pull request merged**
