### PR TITLE
Synchronize with debian package

### PR DESCRIPTION
**Pull request by kapouer**
Hi,
this contains a bit more than a minimal update, so don't hesitate to
ask if you need me to remove some commits.

### CODE REVIEW

**Comment by ebassi** [comment]
Hi @kapouer; I've merged into master various commits that make the patches conflict or redundant. Could you please rebase the Debian packaging on master?

**Comment by kapouer** [comment]
ok, i'm rebasing on master and removing all patches.

**Comment by ebassi** [comment]
Thank you!

**Comment by kapouer** [comment]
Only packaging-related changes. I have to maintain patches separately for debian until version 1.3.2 is published.

**Comment by ebassi** [comment]
I release 1.4.0, as it added new configuration options and API. The branch looks good to me, but if you could update the changelog it would be stellar.

Thanks again, and sorry for taking this long.

**Comment by kapouer** [comment]
Done, and i don't mind waiting.

FYI version 1.3.1 (+ some patches) is the one going to next debian stable (the freeze happened last week), so i'll upload version 1.4.0 to debian/experimental until the debian stretch is actually released.

**Comment by ebassi** [comment]
Stellar. Thanks!

**Pull request merged**
